language: generic
os: 'linux'
dist: 'xenial'
services:
    - docker

before_install:
    - docker build -t csmajer/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true csmajer/react-test npm test

after_success:
    - docker build -t csmajer/multi-client ./client
    - docker build -t csmajer/multi-nginx ./nginx
    - docker build -t csmajer/multi-server ./server
    - docker build -t csmajer/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push csmajer/multi-client
    - docker push csmajer/multi-nginx
    - docker push csmajer/multi-server
    - docker push csmajer/multi-worker

deploy:
    provider: elasticbeanstalk
    region: 'eu-central-1'
    app: 'multi-docker'
    env: 'MultiDocker-env'
    bucket_name: 'elasticbeanstalk-eu-central-1-532309044952'
    bucket_path: 'docker-multi'
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY